package com.BusinessGame.Vyapar.common.enums;

public enum EventType {
    PLAYER_JOINED,
    PLAYER_LEFT,
    HOST_CHANGED,
    GAME_STARTED,
    TURN_CHANGED,
    DICE_ROLLED,
    PLAYER_MOVED,
    PROPERTY_PURCHASED,
    PROPERTY_UPDATED,
    HOUSE_BUILT,
    HOTEL_BUILT,
    RENT_PAID,
    MONEY_UPDATED,
    PROPERTY_MORTGAGED,
    PROPERTY_UNMORTGAGED,
    PLAYER_SENT_TO_JAIL,
    PLAYER_RELEASED,
    RECOVERY_STARTED,
    RECOVERY_COMPLETED,
    PLAYER_BANKRUPT,
    GAME_FINISHED,
    ERROR
}
